export const authorsTypes = {
  // Sync
  SET_AUTHORS: "SET_AUTHORS",

  // TODO: refactor ???
  CLEAR_AUTHORS: "CLEAR_AUTHORS",

  // Async
  GET_AUTHORS_ASYNC: "GET_AUTHORS_ASYNC",
  DELETE_AUTHOR_ASYNC: "DELETE_AUTHOR_ASYNC",
  SEARCH_AUTHOR_ASYNC: "SEARCH_AUTHOR_ASYNC",
};
