export const authorsTypes = {
  // Sync
  SET_AUTHORS: "SET_AUTHORS",
  SET_AUTHOR: "SET_AUTHOR",

  // Async
  GET_AUTHORS_ASYNC: "GET_AUTHORS_ASYNC",
  GET_AUTHOR_ASYNC: "GET_AUTHOR_ASYNC",
  DELETE_AUTHOR_ASYNC: "DELETE_AUTHOR_ASYNC",
  SEARCH_AUTHOR_ASYNC: "SEARCH_AUTHOR_ASYNC",
  ADD_AUTHOR_ASYNC: "ADD_AUTHOR_ASYNC",
  EDIT_AUTHOR_ASYNC: "EDIT_AUTHOR_ASYNC",
};
