export const booksTypes = {
  // Sync
  SET_BOOKS: "SET_BOOKS",
  SET_SEARCH_PATTERN: "SET_SEARCH_PATTERN",
  CLEAR_SEARCH_PATTERN: "CLEAR_SEARCH_PATTERN",

  // Async
  GET_BOOKS_ASYNC: "GET_BOOKS_ASYNC",
  SEARCH_BOOKS_ASYNC: "SEARCH_BOOKS_ASYNC",
  FIND_BOOKS_AUTHOR_BASED_ASYNC: "FIND_BOOKS_AUTHOR_BASED_ASYNC",
};
